// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'postrow': string;
  'span': string;
  'string': string;
}
export const cssExports: CssExports;
export default cssExports;
