// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'postrow': string;
  'postspan': string;
  'poststring': string;
}
export const cssExports: CssExports;
export default cssExports;
