// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cardspan': string;
  'cardstring': string;
  'postcard': string;
}
export const cssExports: CssExports;
export default cssExports;
